### ISSUE TITLE
convert_rst_to_md.yml: Replace ansible.builtin.yum with ansible.builtin.dnf

### ISSUE THREAD

**Issue by 0xFelix** [ansible-collections/community.fqcn_migration#8]
At least for me this line is causing issues on Fedora 39

https://github.com/ansible-collections/community.fqcn_migration/blob/573b307c37147986a26622f5c595ca36d19adf63/roles/fqcn_migration/tasks/utils/convert_rst_to_md.yml#L12

```
fatal: [localhost]: FAILED! => {"changed": false, "msg": ["Could not detect which major revision of yum is in use, which is required to determine module backend.", "You should manually specify use_backend to tell the module whether to use the yum (yum3) or dnf (yum4) backend})"]}
```

It might make sense to replace `ansible.builtin.yum` with `ansible.builtin.dnf`?

**Comment by rpelisse** [comment]
@0xFelix it does! Could you file a PR for that?

**Comment by 0xFelix** [comment]
@rpelisse Done, see #9
